//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manukonda_Assign3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manukonda_Assign3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1402258,Shine,Rainer,Computer Science,2,4.000
        ///1401579,Snicket,Jacques,Computer Science,1,3.867
        ///1560953,West,Gary,Computer Science,0,2.111
        ///1355863,Devereaux,Mark,Computer Science,1,3.998
        ///1500215,Cornvelious,Daniel,Computer Science,1,3.141
        ///1553486,Moore,Jack,Computer Science,3,2.556
        ///1399842,Castle,Richard,Computer Science,3,2.886
        ///1445566,Northwest,Preston,Computer Science,3,3.333
        ///1399234,Buck,Edward,Computer Science,4,2.567
        ///1478201,Waite,Bob,Computer Science,2,3.000
        ///1498765,Hammer,Captain,Computer S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2188_a3_input01 {
            get {
                return ResourceManager.GetString("_2188_a3_input01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSCI,340,C004,4,25
        ///CSCI,240,0001,4,150
        ///CSCI,467,00H3,4,60
        ///CSCI,241,00H2,4,35
        ///CSCI,473,0HP4,3,60
        ///MATH,229,CALC,4,30
        ///MATH,230,CAL2,4,25
        ///MATH,110,0001,3,30
        ///CSCI,401,ABCD,3,25
        ///CSCI,330,0HP3,4,30
        ///CSCI,499,GOTO,1,1
        ///CSCI,466,0002,4,20
        ///MATH,110,0002,3,30
        ///MATH,155,000X,3,25
        ///FLGL,101,EFGH,3,20
        ///FLGL,102,IJKL,3,20
        ///FLGL,201,ZZZZ,3,15
        ///ANTH,220,0001,3,20
        ///PSYC,102,0002,3,50
        ///MGMT,217,0003,3,30
        ///ART,101,0001,3,15
        ///MUSE,394,SING,1,30
        ///STAT,473,MEAN,3,30
        ///PHYS,273,0HP4,4,20
        ///.
        /// </summary>
        internal static string _2188_a3_input02 {
            get {
                return ResourceManager.GetString("_2188_a3_input02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Science
        ///Mathematics
        ///Statistics
        ///Theater
        ///Art
        ///Anthropology
        ///Psychology
        ///Marketing
        ///Physics
        ///Finance
        ///Economics
        ///Biological Sciences
        ///Chemistry
        ///Undecided - Any College.
        /// </summary>
        internal static string _2188_a3_input03 {
            get {
                return ResourceManager.GetString("_2188_a3_input03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1402258,ART,101,C++
        ///1500215,FLGL,101,C++
        ///1402258,FLGL,101,C-
        ///1553486,ANTH,220,C-
        ///1560953,CSCI,466,C++
        ///1421528,MATH,110,F
        ///1478201,MGMT,217,A-
        ///1421528,CSCI,467,C
        ///1399234,CSCI,473,B+
        ///1772123,MATH,110,B-
        ///1513234,MATH,110,B-
        ///1402258,MATH,110,C
        ///1560953,CSCI,240,D
        ///1355863,CSCI,330,B-
        ///1553486,CSCI,473,B-
        ///1355863,CSCI,467,B-
        ///1638171,FLGL,201,C++
        ///1560953,FLGL,201,F
        ///1498765,MATH,230,B-
        ///1399234,CSCI,467,C
        ///1766348,STAT,473,C-
        ///1401579,FLGL,102,F
        ///1231872,CSCI,241,A-
        ///1478201,MATH,155,A
        ///1445566,ART,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2188_a3_input04 {
            get {
                return ResourceManager.GetString("_2188_a3_input04", resourceCulture);
            }
        }
    }
}
